//FOR MOVIES AND SHOWS FETCHING ACTIONS

export const GET_MOVIE_GENRES = "GET_MOVIE_GENRES";
export const GET_TV_GENRES = "GET_TV_GENRES";
export const START_FETCH = "START_FETCH";
export const END_FETCH = "END_FETCH";
export const CLEAR_RESULTS = " CLEAR_RESULTS";
export const GET_MOVIES_BY_GENRE = "GET_MOVIES_BY_GENRE";
export const GET_TVS_BY_GENRE = "GET_TVS_BY_GENRE";
export const GET_MOVIE_LATEST = "GET_MOVIE_LATEST";
export const GET_MOVIE_UPCOMING = "GET_MOVIE_UPCOMING";
export const GET_TRENDING_MOVIES = "GET_TRENDING_MOVIES";
export const GET_ON_AIR_TV_SHOWS = "GET_ON_AIR_TV_SHOWS ";
export const GET_POPULAR_TV_SHOWS = "GET_POPULAR_TV_SHOWS";
export const GET_TOP_RATED_SHOWS = "GET_TOP_RATED_SHOWS";
export const GET_SEARCH_MOVIES_TVS = "GET_SEARCH_MOVIES_TVS";
export const GET_ERROR = "GET ERROR";
